### ISSUE TITLE
Zip files are empty

### ISSUE THREAD

**Issue by Gustry** [kartoza/osm-reporter#146]
Hi,

I tried to download data using InaSAFE or the web interface OSM-Reporter, using only one street with 2-3 buildings. But both return empty zip file.
Maybe the docker container is full? @timlinux Do you have an idea?

Thanks

**Comment by timlinux** [comment]
Thanks for the ticket - going to look at the server now - will update after looing.

**Comment by timlinux** [comment]
OK it seems the disk had filled up. I cleared the /tmp/osm-reporter dir and works again:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/178003/63632932-b77edb80-c648-11e9-9b8d-e18a359d4c1f.png">

Its wierd because I had patched it to clear the tmp dir after each request - will go and see why it doesnt do that...

**Comment by timlinux** [comment]
ok i confirm it is nicely clearing away generated products now but still. caching the .osm file for an hour:

```
root@web:/tmp/osm-reporter# ls -lah 2019-08-24/root/roads/*
total 312K
drwxr-xr-x 2 root root 4.0K Aug 24 07:27 .
drwxrwxrwx 3 root root 4.0K Aug 24 07:27 ..
-rw-r--r-- 1 root root    5 Aug 24 07:27 roadsroads.cpg
-rw-r--r-- 1 root root 300K Aug 24 07:27 roadsroads.zip
root@web:/tmp/osm-reporter# # making a new request now:
root@web:/tmp/osm-reporter# ls -lah 2019-08-24/root/
ls: cannot access '2019-08-24/root/': No such file or directory
root@web:/tmp/osm-reporter# ls -lah 2019-08-24/
ls: cannot access '2019-08-24/': No such file or directory
```

**Comment by Gustry** [comment]
Thanks for the quick fix!

SOmehow, I noticed you were not following this project anymore. (You are not the in the watcher list).
